### ISSUE TITLE
Add smooth scroll 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#12] opened 2021-09-30 20:06 UTC

**Comment by lucasgmelo** [comment] 2021-09-30 20:18
can you assign this issue to me? :)

**Comment by tnmyk** [comment] 2021-09-30 20:52
Scrolling animation?

**Comment by precious-adeyinka** [comment] 2021-09-30 22:27
Hey @swapnilsparsh can you provide more description and assign me after the countdown party please?
Thanks!

**Comment by swapnilsparsh** [comment] 2021-10-01 05:34
> Scrolling animation?

Yes

**Comment by swapnilsparsh** [comment] 2021-10-01 05:35
> Hey @swapnilsparsh can you provide more description and assign me after the countdown party please? Thanks!

You have to use smooth scroll npm package as in some devices website is laggy.

**Comment by swapnilsparsh** [comment] 2021-10-01 05:35
> > Scrolling animation?
> 
> Yes, Would you like to work on this ?

**Comment by Hetu1107** [comment] 2021-10-01 14:57
can i work on this ?

**Comment by precious-adeyinka** [comment] 2021-10-01 21:59
Sure @swapnilsparsh why not, I want to try, even if I don't have all the details, I will research and read up the docs, so maybe you will have to point me to the specific files to modify and what part of the website needs smooth scrolling alright.

**Comment by swapnilsparsh** [comment] 2021-10-02 06:34
> g al

Sure
You have to add a smooth scroll on the full website.
Should I assign this issue to you?

**Comment by swapnilsparsh** [comment] 2021-10-02 06:34
> Sure @swapnilsparsh why not, I want to try, even if I don't have all the details, I will research and read up the docs, so maybe you will have to point me to the specific files to modify and what part of the website needs smooth scrolling alright.

Sure
You have to add a smooth scroll on the full website.
Should I assign this issue to you?

**Comment by Hetu1107** [comment] 2021-10-02 08:29
@swapnilsparsh  can I try on this ?

**Comment by Hetu1107** [comment] 2021-10-02 10:09
hey @swapnilsparsh i have added that smooth scroll but some problem is occuring like on scroll that back to top component is not showing and also on click explore all button.

**Comment by swapnilsparsh** [comment] 2021-10-02 13:12
> hey @swapnilsparsh i have added that smooth scroll but some problem is occuring like on scroll that back to top component is not showing and also on click explore all button.

You might have done something wrong, try to rebase the code with the master branch and then check.

**Comment by Hetu1107** [comment] 2021-10-02 13:23
> > hey @swapnilsparsh i have added that smooth scroll but some problem is occuring like on scroll that back to top component is not showing and also on click explore all button.
> 
> You might have done something wrong, try to rebase the code with the master branch and then check.

I have added one commponent named smooth scroll and added below code in it 

import { useEffect } from "react";
import Scrollbar from 'smooth-scrollbar';
var options = {
    damping: 0.07,
}
const SmoothScroll = () =>{
    useEffect(()=>{
        Scrollbar.init(document.body,options);
    },[])
    return null
}

export default SmoothScroll;

and added smoothscroll comp. in app.js i think the issue is with hash.

**Comment by swapnilsparsh** [comment] 2021-10-02 13:41
> > > hey @swapnilsparsh i have added that smooth scroll but some problem is occuring like on scroll that back to top component is not showing and also on click explore all button.
> > 
> > 
> > You might have done something wrong, try to rebase the code with the master branch and then check.
> 
> I have added one commponent named smooth scroll and added below code in it
> 
> import { useEffect } from "react"; import Scrollbar from 'smooth-scrollbar'; var options = { damping: 0.07, } const SmoothScroll = () =>{ useEffect(()=>{ Scrollbar.init(document.body,options); },[]) return null }
> 
> export default SmoothScroll;
> 
> and added smoothscroll comp. in app.js i think the issue is with hash.

Resolve it by removing the Hash

**Comment by Hetu1107** [comment] 2021-10-02 13:43
> > > > hey @swapnilsparsh i have added that smooth scroll but some problem is occuring like on scroll that back to top component is not showing and also on click explore all button.
> > > 
> > > 
> > > You might have done something wrong, try to rebase the code with the master branch and then check.
> > 
> > 
> > I have added one commponent named smooth scroll and added below code in it
> > import { useEffect } from "react"; import Scrollbar from 'smooth-scrollbar'; var options = { damping: 0.07, } const SmoothScroll = () =>{ useEffect(()=>{ Scrollbar.init(document.body,options); },[]) return null }
> > export default SmoothScroll;
> > and added smoothscroll comp. in app.js i think the issue is with hash.
> 
> Resolve it by removing the Hash

ok let me try

**Comment by B1TSH3LL** [comment] 2021-10-04 17:46
Can I Try This With Coll Animations ???

**Comment by swapnilsparsh** [comment] 2021-10-04 19:44
> Can I Try This With Cool Animations :) Please Assign It To Me

Good Luck 👍🏼

**Comment by B1TSH3LL** [comment] 2021-10-05 04:13
I thaught it was an HTML page to add smooth scroll i didn't started with NPM yet So Sorry Bro I Cant Work On This . :(

**Comment by swapnilsparsh** [comment] 2021-10-14 13:09
> Do you want the smooth scroll, when we click on the up arrow button which scrolls the page to top

Want smooth scroll while scrolling the page.

**Closed** 2021-11-01 06:35 UTC
Labels: enhancement, hacktoberfest, good-first-issue
